### ISSUE TITLE
[AWS] Couldn't get result of Buckets in S3

### ISSUE THREAD

**Issue by userlocalhost2000** [StackStorm/st2contrib#623]
Hi,

The result of actions that return Bucket, e,g `aws.s3_get_bucket` and `aws.s3_get_all_buckets`, couldn't return proper value. They always return `None`.

I confirmed this behavior just only for the actions that return `Bucket` object of S3.
The actions relevant to EC2 return proper results.

Thank you.

**Comment by userlocalhost2000** [comment]
The reason of this problem is failure of serialization of the returned values.

I'll fix it :)

**Comment by ErikThoreson** [comment]
@userlocalhost after this PR it seems certain actions receive the following error "AttributeError: 'module' object has no attribute 'bucket'"

Were you able to get around this? It looks like a problem with boto 2.41.0 and higher

**Comment by userlocalhost** [comment]
@ErikThoreson  Thank you for your report.

I could get buckets information normally.
```
vagrant@st2-node:~$ st2 run aws.s3_get_all_buckets
.
id: 584bc0226f086f0572eacaf4
status: succeeded
parameters: None
result: 
  exit_code: 0
  result:
  - LoggingGroup: http://acs.amazonaws.com/groups/s3/LogDelivery
    creation_date: '2016-11-15T10:45:45.000Z'
    name: 20161115-tmp01
  - LoggingGroup: http://acs.amazonaws.com/groups/s3/LogDelivery
    creation_date: '2016-11-15T11:01:05.000Z'
    name: 20161115-tmp02
  - LoggingGroup: http://acs.amazonaws.com/groups/s3/LogDelivery
    creation_date: '2015-11-20T02:58:47.000Z'
    name: dmzo
  - LoggingGroup: http://acs.amazonaws.com/groups/s3/LogDelivery
    creation_date: '2016-11-14T06:58:25.000Z'
    name: hoge-20161114-02
  stderr: ''
  stdout: ''
vagrant@st2-node:~$
```

And this is my environment of StackStorm.
```
vagrant@st2-node:~$ st2 --version
st2 2.1.0
vagrant@st2-node:~$ /opt/stackstorm/virtualenvs/aws/bin/pip show boto
Name: boto
Version: 2.41.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /opt/stackstorm/virtualenvs/aws/lib/python2.7/site-packages
Requires: 
vagrant@st2-node:~$
```

When possible, cloud you please show me the action that occurs an exception and that stack-trace?

Thank you.
